# Change these first
owner: Kovinda # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: EKEL
    url: https://ekel.kln.ac.lk/login/index.php
    icon: https://cal.kln.ac.lk/pluginfile.php/1/theme_adaptable/favicon/1705034310/favicon.png
    __dangerous__insecure: true
  - name: CAL
    url: https://cal.kln.ac.lk/login/index.php
    icon: https://cal.kln.ac.lk/pluginfile.php/1/theme_adaptable/favicon/1705034310/favicon.png
  - name: KLN Medicine
    url: https://medicine.kln.ac.lk/
    icon: https://cal.kln.ac.lk/pluginfile.php/1/theme_adaptable/favicon/1705034310/favicon.png
  - name: Kelaniya University
    url: https://www.kln.ac.lk/
    icon: https://cal.kln.ac.lk/pluginfile.php/1/theme_adaptable/favicon/1705034310/favicon.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: https://uptime.kovinda.eu.org/
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Kovinda/res/master/img/K/safari-pinned-tab.svg
  name: Uptime
  # introTitle: "Uptime monitor and status page, powered by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Insta
      href: https://www.instagram.com/kovinda_thisal/


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
